"""empty message

Revision ID: 7a5eda0351c8
Revises: 71d4067e4748
Create Date: 2017-03-01 21:37:10.032905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a5eda0351c8'
down_revision = '71d4067e4748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journey', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journey', 'date_created')
    # ### end Alembic commands ###
