"""empty message

Revision ID: d1ce95a01ab3
Revises: a8f2740a698d
Create Date: 2017-05-08 19:31:11.544409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1ce95a01ab3'
down_revision = 'a8f2740a698d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=64), nullable=True))
    # op.create_unique_constraint(None, 'user', ['username'])  # TODO - sqlite cannot alter constraints
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'user', type_='unique')  # TODO - sqlite cannot alter constraints
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
